---
title: "Readme"
format: md
editor: 
  markdown: 
    wrap: 72
---

## Correlation of median income by county in CA and quantity of FEMA declared disasters, 2012-2022

The Flint, Michigan water crisis and the Pajaro Valley flood are two
textbook examples of environmental racism which arose because of
extremely neglected infrastructure in impoverished communities.
Instances of outdated infrastructure endangering communities is not
surprising or new, but I wanted to explore further in the case of a FEMA
data set containing observations on federally declared disasters. Based
on the past case studies mentioned above as well as many others, I
hypothesize that an inverse correlation between median household income
and declared disasters will be found by the use of lasso regression.

SOI bases its county income data on the addresses reported on individual
income tax returns filed with the IRS. Data are presented by county
(including State totals) and are available for Tax Years1989through
2022. The data include; number of returns, which approximates the number
of households, number of personal exemptions, which approximates the
population, adjusted gross income (AGI), wages and salaries, dividends
before exclusion, interest received, and more.

Disaster Declarations Summaries is a summarized dataset describing all
federally declared disasters. This dataset lists all official FEMA
Disaster Declarations, beginning with the first disaster declaration in
1953 and features all three disaster declaration types: major disaster,
emergency, and fire management assistance. The dataset includes declared
recovery programs and geographic areas (county not available before
1964; Fire Management records are considered partial due to historical
nature of the dataset).

Glimpse function

```{r}

library(tidyverse)

rawdata1_AGIbyCounty <- read.csv("~/Documents/stat155/Project 1/data/rawdata/Raw_AGI_by_State/12cyallagi.csv")
glimpse(rawdata1_AGIbyCounty)

rawdata2_FEMAdisaster <- read.csv("~/Documents/stat155/Project 1/data/rawdata/DisasterDeclarationsSummaries")
glimpse(rawdata2_FEMAdisaster)

```
