---
title: "Readme"
format: md
editor: 
  markdown: 
    wrap: 72
---

## What is the correlation between median income by zip code and lead certifications

Narrative: The Flint, Michigan water crisis and the Pajaro Valley flood
are two textbook examples of environmental racism which arose because of
extremely neglected infrastructure in impoverished communities.
Instances of dilapidated infrastructure causing serious health issues is
not surprising or new, but I wanted to explore further in the case of a
data set containing observations on which houses in Philadelphia were
given lead free certifications. Based on past knowledge, I hypothesize
that an inverse correlation between median household income and lead in
houses exists and I will test this using a form of linear regression.

The Philadelphia Lead Paint Disclosure and Certification Law requires
owners of property built before 1978 to provide a certification that a
property is lead free\
or lead safe before it may be rented to a tenant (either a new or
renewed lease, formal or informal). This certification (or statement of
exemption) must be submitted to the Lead and Healthy Homes Program
through the Lead Certification Submission System a requirement to obtain
a rental license. This data set provides the current certification
status of each property in the city by OPA account number, based on the
information submitted to the Lead and Healthy Homes Program. Field cases
include when the house was built (and therefore whether it is exempt
from requiring a certifications), if a certification was issued, the
most recent issuing and expiration date of said certification, building
category, and more.

Glimpse function

```{r}

library(tidyverse)

rawdata1_lead_certifications <- read.csv("~/Documents/stat155/Project 1/data/rawdata1_lead_certifications.csv")

glimpse(rawdata1_lead_certifications)

```
